name: Hello world Docker Image Build & Publish

on:
  push:
    branches: [ albertsebastian1-hw-1 ]
  pull_request:
    branches: [ albertsebastian1-hw-1 ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # Check out the repository
    - uses: actions/checkout@v2

    # Setting Github authentication to checkout the code to GITHUB_WORKSPACE
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        # Registry github container register
        # Supported container image formats, please refer https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#about-container-registry-support
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    # Performing go test with the latest code before Docker image build
    - name: Testing hello world REST API
      id: test
      run: go test -v 

    # Build docker image
    - name: Build the Docker image
      if: steps.test.outputs.exit_code == 0
      run: docker build . --file Dockerfile --tag ghcr.io/albertsebastian1/helloworld:latest

    # Publish Docker image to github container registry
    - name: Publish Docker image
      run: docker push ghcr.io/albertsebastian1/helloworld:$GITHUB_RUN_ID