name: Hellow world Docker Image Build

on:
  push:
    branches: [ albertsebastian1-hw-1 ]
  pull_request:
    branches: [ albertsebastian1-hw-1 ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag alberthw:latest
