name: Hello world Docker Image Build & Publish

on:
  push:
    branches: [ albertsebastian1-hw-1 ]
  pull_request:
    branches: [ albertsebastian1-hw-1 ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/albertsebastian1/helloworld:latest
    - name: Publish Docker image
      run: docker push ghcr.io/albertsebastian1/helloworld:latest